export const dataInfo = {
  first: {
    name: 'Maryna',
    secondName: 'Bielozorova',
    position: 'Manual and automation QA engineer',
    email: 'mar.belozerova@gmail.com',
    phone: '+38 (097) 752-37-73',
    socials: {
      linkedin: {
        name: 'linkedin.com/in/maryna-bielozorova',
        url: 'https://www.linkedin.com/in/maryna-bielozorova/',
      },
      telegram: {
        name: 'Maryna',
        url: 'tg://resolve?domain=mar_beloz',
      },
      github: {
        name: 'Maryna Bielozorova',
        url: 'http://github.com/m-bielozorova',
      },
    },
  },
  experience: {
    title: 'Professional experience',
    description:
      'Below are select projects demonstrating my expertise in manual and automated testing across diverse domains. Each project showcases specific challenges I solved, technologies I implemented, and measurable improvements delivered to development teams and end users.',
    jobs: [
      {
        id: 'j-01',
        fromYear: '2021',
        fromMonth: 'April',
        toYear: 'Present',
        toMonth: '',
        companyName: 'Treeum',
        companyCity: 'Kyiv',
        position: 'Manual and automation QA engineer',
        achievements: [
          'Started learning JavaScript/TypeScript to expand automation capabilities',
          'Mastered the Playwright framework for web testing',
          'Successfully migrated automation tests from Selenide/Java to Playwright/TypeScript',
          'Reduced test execution time from 30 minutes to 15 minutes after migration to Playwright',
          'Performed log analysis in Grafana and error tracking in Sentry',
          'Started manual testing of mobile applications on both iOS and Android platforms',
          'Began learning mobile app automation using the Detox framework',
        ],
        responsibilities: [
          'Analyze requirements and create test documentation (test cases, bug reports, test summary reports)',
          'Perform functional, integration, regression, smoke, usability, cross-browser, and ad-hoc testing',
          'Perform API testing (REST API) using Postman and Playwright',
          'Test mobile applications (iOS/Android)',
          'Analyze logs and system errors to identify root causes',
          'Collaborate with the support team to investigate and reproduce user-reported issues',
          'Creating automated tests (approx. 40% of working time) using: Java, Selenide, JUnit, Gradle, Allure; JavaScript/TypeScript, Playwright',
          'Work across multiple projects in collaboration with developers',
        ],
      },
      {
        id: 'j-02',
        fromYear: '2019',
        fromMonth: 'August',
        toYear: '2021',
        toMonth: 'March',
        companyName: 'SmartyAds',
        companyCity: 'Kyiv',
        position: 'Manual QA engineer',
        responsibilities: [
          'Analyzing project requirements and technical documentation',
          'Testing company’s web applications and internal systems',
          'Creating and executing test cases, test runs, bug reports, and test summary reports',
          'Performed functional, regression, usability, smoke, and ad-hoc testing',
          'Contributed to automation test coverage from scratch (Java, Selenium WebDriver, TestNG, Maven, Allure)',
          'Communicated with developers to clarify issues and ensure timely resolution',
          'Participated in team meetings and providing feedback on product quality',
        ],
        achievements: [
          'Learned the programming language Java',
          'Learned Selenium/Selenide framework for web testing',
          'Learned TestNG, Gradle, Allure for test automation',
          'Created automated tests for web applications using Java, Selenide, TestNG, Gradle, Allure',
        ],
      },
      {
        id: 'j-03',
        fromYear: '2018',
        fromMonth: 'December',
        toYear: '2019',
        toMonth: 'August',
        companyName: 'Technomatix',
        companyCity: 'Kyiv',
        position: 'Junior Manual QA Engineer',
        responsibilities: [
          'Analyzed business and technical requirements for e-learning web platforms',
          'Performed manual testing of educational systems, focusing on stability and user experience',
          'Created and executed test cases, test runs, bug reports, and test summary reports',
          'Performed regression testing to ensure functionality after updates or fixes',
          'Participated in multiple parallel projects across different teams',
          'Collaborated with developers to troubleshoot bugs and align on solutions',
          'Actively proposed improvements to product functionality and usability',
        ],
        achievements: [
          'Quickly adapted to QA role and manual testing in real projects',
          'Found critical bugs during regression testing, helping avoid release issues',
        ],
      },
    ],
  },
  about: {
    title: 'About My Self',
    shortDesc:
      'Skilled in creating and running tests for frontend and backend parts of applications.',
    description: {
      partOne:
        'QA Engineer with experience in end-to-end testing of web applications. I work with both manual testing and test automation, and I am good at API testing and checking if applications work well on different browsers and devices.',
      partTwo:
        "What makes me different is that I think about both technical problems and user experience. I don't just find bugs - I also check how problems affect real users. My careful approach to creating tests has helped prevent serious issues from going live in FinTech, AdTech, and education projects.",
      partThree:
        'I work well in teams where everyone cares about quality. I enjoy helping team members learn better testing methods, and I keep learning new automation tools and frameworks to improve my skills.',
    },
    skills: [
      {
        count: 1,
        title: 'QA docs and reports',
        img: '/images/first.svg',
        array: [
          'Test case',
          'Check list',
          'Bug report',
          'Test run report',
          'Test summary report',
        ],
      },
      {
        count: 2,
        title: 'Front-end testing',
        img: '/images/second.svg',
        array: [
          'HTML / CSS3',
          'JavaScript / TypeScript',
          'Adaptive layout',
          'Responsible layout',
          'Black / Gray box testing',
          'Integration testing',
          'E2E testing',
        ],
      },
      {
        count: 3,
        title: 'Back-end testing',
        img: '/images/third.svg',
        array: [
          'REST API testing',
          'API JSON Schemas testing',
          'Mocking test data',
        ],
      },
      {
        count: 4,
        title: 'Automation testing',
        img: '/images/five.svg',
        array: [
          'JavaScript / TypeScript',
          'Playwright',
          'REST API testing',
          'API json schema validation',
          'e2e smoke & regression testing',
        ],
      },
      {
        count: 5,
        title: 'DevOps and VCS',
        img: '/images/fourth.svg',
        array: ['CI / CD', 'GitLab', 'GitHub', 'Testing Management System'],
      },
      {
        count: 6,
        title: 'Soft and Tools',
        img: '/images/sixth.svg',
        array: [
          'Git',
          'Postman',
          'Playwright',
          'Proxyman',
          'Youtrack / Jira',
          'Testomat.io',
        ],
      },
    ],
  },
  contactMe: {
    title: 'Contact me',
    description:
      'Do you need help with testing your web applications or want to discuss QA automation? I am ready to help with your project or answer questions about testing strategies. Feel free to reach out - I would be happy to discuss how we can work together to make your software better.',
  },
  skills: {
    techSkills: [
      'HTML5',
      'CSS3',
      'JavaScript / TypeScript',
      'Git/GitHub',
      'CI/CD',
      'Regression testing',
      'Smoke & Sanity Testing',
      'Integration Testing',
      'API Testing',
      'Cross-browser testing',
      'Mobile testing (iOS/Android)',
      'End-to-End Testing (E2E)',
    ],
    softSkills: [
      'Analytical thinking',
      'Communication',
      'Team Player',
      'Quick learner',
      'Result-oriented',
      'Punctuality',
      'Problem-solving',
      'Attention to detail',
      'Perseverance and commitment to continuous learning',
    ],
    toolsSkills: [
      'Playwright',
      'Postman',
      'Jira/YouTrack',
      'TestRail',
      'Testomat.io',
      'Figma',
      'Grafana',
      'Sentry',
      'Chrome DevTools',
      'Postman',
      'Proxyman',
      'Clarity',
      'Smartlook',
      'Stoplight',
      'BrowserStack',
    ],
  },
  summary: {
    description:
      'Experienced QA Engineer (6+ years) with expertise in test automation across diverse domains: e-learning platforms, AdTech systems, and FinTech products. Led complete test suite migration from Java/Selenide to TypeScript/Playwright, implemented CI/CD integration. Specialize in cross-browser testing, API testing (Postman/Playwright), mobile QA (iOS/Android).',
  },
  educations: [
    {
      certification: 'Manual QA Engineer',
      company: 'GOIT Academy',
      year: '2018',
      city: 'Kyiv',
    },
    {
      certification: 'QA Automation Engineer',
      company: 'Hillel IT School',
      year: '2020',
      city: 'Kyiv',
    },
    {
      certification: 'QA Automation Engineer',
      company: 'Yet Another QA School',
      year: '2025',
      city: 'Kyiv',
    },
    {
      certification: 'Accounting and Audit',
      company: 'Bila Tserkva National Agrarian University',
      year: '2011 - 2012',
      city: 'Bila Tserkva',
    },
  ],
  languages: [
    {
      name: 'English',
      level: 'Intermediate',
    },
    {
      name: 'Ukrainian',
      level: 'Native',
    },
  ],
};
